apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: tds-group-3
data:
  PORT: "3000"
  DB_PORT: "5432"
  JWT_EXPIRES_IN: "7d"
  ACCESS_TOKEN_EXPIRES_IN: "15m"
  REFRESH_TOKEN_EXPIRES_IN: "7d"
  APP_URL: "https://tds-group-3.tds-linar.udesa.edu.ar"
  MOBILE_RESET_PASSWORD_URL: "exp://tds-group-3.tds-linar.udesa.edu.ar/--/reset-password"
  ALLOWED_EMAIL_DOMAIN: "udesa.edu.ar"
  SMTP_PORT: "587"
  SMTP_FROM: "noreply@udesa.edu.ar"
  FRIENDS_SERVICE_URL: "http://friends:3000"
