apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: tds-group-3
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${USERS_DB_NAME}"
  DB_USER: "${USERS_DB_USER}"
  DB_PASSWORD: "${USERS_DB_PASSWORD}"
  DB_ADMIN_USER: "${USERS_DB_ADMIN_USER}"
  DB_ADMIN_PASSWORD: "${USERS_DB_ADMIN_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  SMTP_HOST: "${SMTP_HOST}"
  SMTP_PORT: "${SMTP_PORT}"
  SMTP_USER: "${SMTP_USER}"
  SMTP_PASS: "${SMTP_PASS}"
  SMTP_FROM: "${SMTP_FROM}"
