name: CI

on:
  push:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Test summary
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            await core.summary
              .addHeading('Test Results')
              .addTable([
                [{data: 'Step', header: true}, {data: 'Status', header: true}],
                ['Unit tests (npm run test)', '${{ job.status }}']
              ])
              .write()