name: CI

on:
  push:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: udesa-software/users
          files: ./coverage/lcov.info
          flags: unit
          fail_ci_if_error: true

      - name: Test summary
        if: always()
        uses: actions/github-script@v8
        with:
          script: |
            await core.summary
              .addHeading('Test Results')
              .addTable([
                [{data: 'Step', header: true}, {data: 'Status', header: true}],
                ['Unit tests (npm run test:coverage)', '${{ job.status }}']
              ])
              .write()